Dom library
trekab/library pull request #1
Opened 2020-05-06 20:44 UTC by trekab

## Project: Library:

In this project we:
- Added the Library HTML.
- Added JS functionality for adding and removing books from the library.
- Added ability for the user to toggle the read status of any book in the library.

2020-05-07 10:40 UTC, bellom requested changes
## Hi Team:clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-05-07 10:40 UTC, bellom commented on js/script.js
> +function createCard(book, id) {
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-05-08 10:43 UTC, shloch approved these changes
## Good to go
Logic and DOM manipulation are seprate
App is beautiful
![Screen Shot 2020-05-08 at 11 46 49 AM](https://user-images.githubusercontent.com/40712459/81398397-0dd17300-9121-11ea-81c6-0f9c5e14bf4c.png)

2020-05-09 01:18 UTC, trekab commented
Thank you @bellom and @shloch for the timely code reviews. :smile:

2020-05-09 01:18 UTC, merged